In [1]:
from dotenv import load_dotenv
import os

import pandas as pd
load_dotenv()

True

In [2]:
folder = os.getenv("DATA_PATH")

file_path = os.path.join(folder, "edges.csv")
df = pd.read_csv(file_path, sep="\t", header=0)

df.head(2)

,ocid_object,ocid_subject,subject,original_ocid_relation,object,timestamp,store_source_link,store_source_date,number_of_occurrences,relation_type,subject_domain,object_domain,ocid_relation
0,101000001708,102100016267,KPNA6,232000000917,mouse Anp32a,1.640995e+09,s3://ai.dimensions.data/publications/20220105/...,2022-01-19,1.0,AFFECTS_ACTIVITY_OF,HUMAN_GENES,PROTEIN,1451765542
1,101000001708,102100016267,KPNA6,232000000125,mouse Anp32a,1.640995e+09,s3://ai.dimensions.data/publications/20220105/...,2022-01-19,2.0,RELATES_TO,HUMAN_GENES,PROTEIN,4235515068

In [3]:
num_rows = df.shape[0]

df_cleaned = df.dropna()

ratio = df_cleaned.shape[0]/num_rows
print(f"{df.shape} {df_cleaned.shape} {ratio*100:2f}")

(22211887, 13) (22192583, 13) 99.913092

In [5]:
from datetime import datetime
df_cleaned["year"] = df_cleaned.timestamp.apply(lambda x: datetime.fromtimestamp(x).year)

/tmp/ipykernel_567311/2306138816.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned["year"] = df_cleaned.timestamp.apply(lambda x: datetime.fromtimestamp(x).year)

In [12]:
cond

0           False
1           False
2           False
3           False
4           False
            ...
22211882    False
22211883    False
22211884    False
22211885    False
22211886    False
Name: year, Length: 22192583, dtype: bool

In [9]:
cond =(df_cleaned.year < 2003) & (df_cleaned.year > 1970)
small_df = df_cleaned[cond]
small_df.shape

(5003872, 14)

In [10]:
small_file_path = os.path.join(folder + "_small", "edges.csv")
small_file_path

'/home/pablo.sanchez2/Documents/GitHub/data/hakken_bio/v2_small/edges.csv'

In [13]:
small_df.head()

,ocid_object,ocid_subject,subject,original_ocid_relation,object,timestamp,store_source_link,store_source_date,number_of_occurrences,relation_type,subject_domain,object_domain,ocid_relation,year
16,101000009702,101000402312,xenopus laevis foxd1,232000000917,Lactobacillus rhamnosus dltB,915148800.0,s3://ai.dimensions.data/publications/20220105/...,1999-01,2.0,AFFECTS_ACTIVITY_OF,PROTEIN,PROTEIN,1110109109,1999
17,101000009702,101000402312,xenopus laevis foxd1,232000000917,Lactobacillus rhamnosus dltB,915148800.0,s3://ai.dimensions.data/publications/20220105/...,1999-01,2.0,DECREASES_ACTIVITY_OF,PROTEIN,PROTEIN,2256740993,1999
18,101000009702,101000436480,Patiria pectinifera tbr1,232000000917,Lactobacillus rhamnosus dltB,946684800.0,s3://ai.dimensions.data/publications/20220105/...,2000-02,1.0,DECREASES_ACTIVITY_OF,PROTEIN,PROTEIN,2256740993,2000
19,101000009702,101000436480,Patiria pectinifera tbr1,232000000917,Lactobacillus rhamnosus dltB,946684800.0,s3://ai.dimensions.data/publications/20220105/...,2000-02,1.0,AFFECTS_ACTIVITY_OF,PROTEIN,PROTEIN,1110109109,2000
23,101000009702,101700004750,IHH,232000000890,Lactobacillus rhamnosus dltB,915148800.0,s3://ai.dimensions.data/publications/20220105/...,1999-05,2.0,MODULATES,PROTEIN,PROTEIN,623604654,1999

In [16]:
small_df.to_csv(small_file_path, sep="\t")