In [8]:
import polars as pl

In [9]:
nodes_df = pl.read_csv(
    "s3://sai-spaice-ds/data/processed/data_processing/pubtator3-v0.4.0/nodes_corrected.tsv",
    separator="\t",
)
facts_df = pl.read_csv(
    "s3://sai-spaice-ds/data/processed/data_processing/pubtator3-v0.4.0/edges.tsv", separator="\t"
)

In [10]:
facts_df.head()

shape: (5, 10)
┌────────────┬────────────┬────────────┬──────┬───┬────────────┬───────────┬───────────┬───────────┐
│ subject_id ┆ relation_t ┆ object_id  ┆ year ┆ … ┆ object_dom ┆ subject_i ┆ object_id ┆ number_of │
│ ---        ┆ ype        ┆ ---        ┆ ---  ┆   ┆ ain        ┆ d_raw     ┆ _raw      ┆ _occurren │
│ str        ┆ ---        ┆ str        ┆ i64  ┆   ┆ ---        ┆ ---       ┆ ---       ┆ ces       │
│            ┆ str        ┆            ┆      ┆   ┆ str        ┆ str       ┆ str       ┆ ---       │
│            ┆            ┆            ┆      ┆   ┆            ┆           ┆           ┆ i64       │
╞════════════╪════════════╪════════════╪══════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 0003fb22e2 ┆ ASSOCIATE  ┆ 2a57ef5e28 ┆ 2014 ┆ … ┆ GENE       ┆ 12400     ┆ 12842     ┆ 1         │
│ 049da4ab2c ┆            ┆ 7a4d2b1bc3 ┆      ┆   ┆            ┆           ┆           ┆           │
│ 993efa06f7 ┆            ┆ cb68a39bf1 ┆      ┆   ┆            ┆           ┆           ┆           │
│ …          ┆            ┆ …          ┆      ┆   ┆            ┆           ┆           ┆           │
│ 0003fb22e2 ┆ ASSOCIATE  ┆ 87a3925958 ┆ 1994 ┆ … ┆ GENE       ┆ 12400     ┆ 17523     ┆ 2         │
│ 049da4ab2c ┆            ┆ 4f0df97902 ┆      ┆   ┆            ┆           ┆           ┆           │
│ 993efa06f7 ┆            ┆ 86fa4ce057 ┆      ┆   ┆            ┆           ┆           ┆           │
│ …          ┆            ┆ …          ┆      ┆   ┆            ┆           ┆           ┆           │
│ 0003fb22e2 ┆ NEGATIVE_C ┆ f229d8118b ┆ 2018 ┆ … ┆ GENE       ┆ 12400     ┆ 54199     ┆ 1         │
│ 049da4ab2c ┆ ORRELATE   ┆ dbd6442922 ┆      ┆   ┆            ┆           ┆           ┆           │
│ 993efa06f7 ┆            ┆ 6bdc28f03f ┆      ┆   ┆            ┆           ┆           ┆           │
│ …          ┆            ┆ …          ┆      ┆   ┆            ┆           ┆           ┆           │
│ 0004388cac ┆ PREVENT    ┆ 38720b76d8 ┆ 2009 ┆ … ┆ DISEASE    ┆ HGVS:c.15 ┆ MESH:D006 ┆ 1         │
│ 249917f776 ┆            ┆ 3a57a04d5b ┆      ┆   ┆            ┆ 27_1528de ┆ 509       ┆           │
│ baf7bcd447 ┆            ┆ 763dc08634 ┆      ┆   ┆            ┆ l;Corresp ┆           ┆           │
│ …          ┆            ┆ …          ┆      ┆   ┆            ┆ ond…      ┆           ┆           │
│ 00048b289b ┆ NEGATIVE_C ┆ a4a1037a39 ┆ 2017 ┆ … ┆ GENE       ┆ 14313     ┆ 16323     ┆ 1         │
│ 2a5de15aa7 ┆ ORRELATE   ┆ 0964cd8ae6 ┆      ┆   ┆            ┆           ┆           ┆           │
│ 833e5fc934 ┆            ┆ 30808fec7b ┆      ┆   ┆            ┆           ┆           ┆           │
│ …          ┆            ┆ …          ┆      ┆   ┆            ┆           ┆           ┆           │
└────────────┴────────────┴────────────┴──────┴───┴────────────┴───────────┴───────────┴───────────┘

In [12]:
relation_types = facts_df["relation_type"].unique()

In [14]:
relation_types

shape: (12,)
Series: 'relation_type' [str]
[
	"STIMULATE"
	"DRUG_INTERACT"
	"TREAT"
	"NEGATIVE_CORRELATE"
	"POSITIVE_CORRELATE"
	…
	"COMPARE"
	"COTREAT"
	"INTERACT"
	"CAUSE"
	"ASSOCIATE"
]

In [13]:
nodes_df.head()

shape: (5, 5)
┌─────────────────────┬─────────────┬────────────────────┬────────────────────┬────────────────────┐
│ node_id             ┆ node_domain ┆ node_id_raw        ┆ node_name          ┆ node_domain_id     │
│ ---                 ┆ ---         ┆ ---                ┆ ---                ┆ ---                │
│ str                 ┆ str         ┆ str                ┆ str                ┆ str                │
╞═════════════════════╪═════════════╪════════════════════╪════════════════════╪════════════════════╡
│ 0009ad04c8987619d66 ┆ GENE        ┆ 29547397           ┆ PBOR_RS12800       ┆ 1fb687612b24dddaac │
│ a00dceb4386…        ┆             ┆                    ┆                    ┆ 8cb9635b9462…      │
│ 001c6cfebaba7d7927b ┆ DNAMUTATION ┆ RS#:4950928;Corres ┆ RS#:4950928;       ┆ 6ef835a9c3c62d595f │
│ 0a197195fb7…        ┆             ┆ pondingGene:…      ┆ (CHI3L1)           ┆ 324e50781265…      │
│ 00263ee4fbf9e985397 ┆ DNAMUTATION ┆ HGVS:c.110-2A>T;Co ┆ HGVS:c.110-2A>T;   ┆ 6ef835a9c3c62d595f │
│ b408af40fb1…        ┆             ┆ rrespondingG…      ┆ (ACAD8)            ┆ 324e50781265…      │
│ 0033a95d509b8116c13 ┆ DNAMUTATION ┆ HGVS:c.14C&gt;T    ┆ HGVS:c.14C&gt;T    ┆ 6ef835a9c3c62d595f │
│ 18d23fd986a…        ┆             ┆                    ┆                    ┆ 324e50781265…      │
│ 003b8558ea81c0890ec ┆ DNAMUTATION ┆ RS#:199422241(Expi ┆ RS#:199422241(Expi ┆ 6ef835a9c3c62d595f │
│ defeed92c27…        ┆             ┆ red);HGVS:c.…      ┆ red);HGVS:c.…      ┆ 324e50781265…      │
└─────────────────────┴─────────────┴────────────────────┴────────────────────┴────────────────────┘

In [9]:
foxo_rows = nodes_df.filter(
    (pl.col("node_name").str.contains("(?i)foxo3")) & (pl.col("node_domain") == "GENE")
)

for row in foxo_rows.select(["node_domain", "node_name", "node_id_raw"]).iter_rows():
    node_domain, node_name, node_id_raw = row
    print(f"{node_name} | {node_id_raw} || {node_domain}")

FOXO3 | 2309 || GENE
foxo3b | 102217263 || GENE
foxo3b | 100301621 || GENE
FOXO3 | 101799850 || GENE
foxo3b | 100700657 || GENE
foxo3.L | 444992 || GENE
FOXO3 | 535530 || GENE
FOXO3 | 700731 || GENE
Foxo3 | 100770315 || GENE
Foxo3 | 56484 || GENE
FOXO3 | 733621 || GENE
FOXO3 | 421769 || GENE
FOXO3B | 2310 || GENE
foxo3a | 494532 || GENE
FOXO3 | 481954 || GENE
FOXO3 | 100913151 || GENE
foxo3b | 30296 || GENE
Foxo3 | 294515 || GENE

In [10]:
foxo_rows

shape: (18, 5)
┌─────────────────────────────┬─────────────┬─────────────┬───────────┬────────────────────────────┐
│ node_id                     ┆ node_domain ┆ node_id_raw ┆ node_name ┆ node_domain_id             │
│ ---                         ┆ ---         ┆ ---         ┆ ---       ┆ ---                        │
│ str                         ┆ str         ┆ str         ┆ str       ┆ str                        │
╞═════════════════════════════╪═════════════╪═════════════╪═══════════╪════════════════════════════╡
│ fac2a637e1c57627dd78b9d53eb ┆ GENE        ┆ 2309        ┆ FOXO3     ┆ 1fb687612b24dddaac8cb9635b │
│ 706…                        ┆             ┆             ┆           ┆ 9462…                      │
│ ddf1386dc4a5b7ee907ddcdcc1b ┆ GENE        ┆ 102217263   ┆ foxo3b    ┆ 1fb687612b24dddaac8cb9635b │
│ ade…                        ┆             ┆             ┆           ┆ 9462…                      │
│ e28d7cf3ded8127e74250c89711 ┆ GENE        ┆ 100301621   ┆ foxo3b    ┆ 1fb687612b24dddaac8cb9635b │
│ a8d…                        ┆             ┆             ┆           ┆ 9462…                      │
│ 3b3f5b3b7213942e6f048aa2743 ┆ GENE        ┆ 101799850   ┆ FOXO3     ┆ 1fb687612b24dddaac8cb9635b │
│ a70…                        ┆             ┆             ┆           ┆ 9462…                      │
│ 8691687f12495910e2c1e5135c7 ┆ GENE        ┆ 100700657   ┆ foxo3b    ┆ 1fb687612b24dddaac8cb9635b │
│ 58b…                        ┆             ┆             ┆           ┆ 9462…                      │
│ …                           ┆ …           ┆ …           ┆ …         ┆ …                          │
│ df6e817dafe100db5e56910e5b2 ┆ GENE        ┆ 494532      ┆ foxo3a    ┆ 1fb687612b24dddaac8cb9635b │
│ 6a8…                        ┆             ┆             ┆           ┆ 9462…                      │
│ 9131fdb42872d69bb10d28a6abb ┆ GENE        ┆ 481954      ┆ FOXO3     ┆ 1fb687612b24dddaac8cb9635b │
│ df9…                        ┆             ┆             ┆           ┆ 9462…                      │
│ a523b07f4bd9de41e041e82ef02 ┆ GENE        ┆ 100913151   ┆ FOXO3     ┆ 1fb687612b24dddaac8cb9635b │
│ 394…                        ┆             ┆             ┆           ┆ 9462…                      │
│ e26aefd8d5e664546bbc0fd4ec9 ┆ GENE        ┆ 30296       ┆ foxo3b    ┆ 1fb687612b24dddaac8cb9635b │
│ 430…                        ┆             ┆             ┆           ┆ 9462…                      │
│ edb88a82f2cd987aa01196333bb ┆ GENE        ┆ 294515      ┆ Foxo3     ┆ 1fb687612b24dddaac8cb9635b │
│ f5e…                        ┆             ┆             ┆           ┆ 9462…                      │
└─────────────────────────────┴─────────────┴─────────────┴───────────┴────────────────────────────┘